### ISSUE TITLE
Severe bug which randomly changes the assignment between cleaning techniques and result metrics in the output 

### ISSUE THREAD

**Issue by sscdotopen** [chu-data-lab/CleanML#3]
Hi,

First of all: thanks for creating CleanML, its a super interesting experimentation framework, and we are using it for our ongoing research on the connection of data quality and fairness.

Unfortunately, we found a **severe bug in CleanML**, which should be fixed as soon as possible, as it potentially renders a lot of the results computed with CleanML unreliable.

We noticed that we got strange results when running the same experiment twice. The screenshot below shows the outputs from two subsequent runs of the same experiment. The actual accuracy/f1 numbers are the same, but the order and assignment of the keys (the cleaning techniques) is different.

![afbeelding](https://github.com/chu-data-lab/CleanML/assets/409707/ba616c40-b349-4f13-8400-34640ace3d5a)

This comes from a bug which may sometimes randomly reorder the list of cleaning techniques (but not the corresponding cleaned test sets...) The issue is caused by the following line of code in https://github.com/chu-data-lab/CleanML/blob/7db26e620dc1cf693a8f32e89849eda601fd219b/experiment.py#L33

We think that this code is intended to filter the `test_files` list, however, it converts it to a set for that. Sets have no order, so converting a list to a set and back means that the order of the contained items can randomly change. 

We confirmed that this happens by printing the list before and after this line:
![afbeelding](https://github.com/chu-data-lab/CleanML/assets/409707/7f239e71-d1db-4d82-8d11-8bbec9e476c3)

The code after this line in https://github.com/chu-data-lab/CleanML/blob/7db26e620dc1cf693a8f32e89849eda601fd219b/experiment.py#L36
implicitly assumes that the `X_test_list`, `y_test_list` and `test_files` lists are correctly aligned, however the last list is randomly reordered, which means that the cleaning results are also randomly reordered.

We fixed this bug in our fork (and will now rerun several thousands of experiments), and we wanted to point it out here as well, so that you can fix it in the original code.

**Comment by LiPengCS** [comment]
Thanks for your interest in our paper and pointing out this bug. I sincerely apologize for any inconvenience it may have caused. We have fixed the bug in the original code.

**Comment by sscdotopen** [comment]
Thank you for addressing this, Peng!
